[workspace]
members = [
    "mdbook-discord-components",
    "mdbook-discord-components-derive",
    "mdbook-discord-components-wasm",
]

[profile.release]
opt-level = "s"

[profile.release.package.mdbook-discord-components]
opt-level = 3
